### ISSUE TITLE
About classifier free guidance

### ISSUE THREAD

**Issue by okaris** [haoosz/ViCo#8]
I was wondering how ViCo handles classifier free guidance without sacrificing compute time

**Comment by haoosz** [comment]
We apply the same operation in conditional and unconditional branches where the only difference is that one uses the given prompt while the other uses the null text. Given a prompt, we have the position of S* in the text tokens for the conditional branch. We use the same position for the unconditional one. There, we add equal overhead, which is subtle, to the conditional and unconditional diffusion processes.

**Comment by okaris** [comment]
Thank you @haoosz 

I assumed for the null text the mask would be zeros. I will try again with how you explained above.

**Comment by okaris** [comment]
@haoosz I've been experimenting with this and I'm a bit confused about using the same positions for unconditional branch (or negative conditioning) 

If the text is null or different from the "positive" prompt, how can same positions still work? If the S* is not in the prompt wouldn't running it without image cross attention make more sense? Am I missing something here?
